# Generated by Django 4.2 on 2025-11-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cocacola', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField()),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cocacola.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cocacola.proveedor')),
            ],
        ),
    ]
