# Generated by Django 5.1 on 2025-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cocacola', '0004_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flota_produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(max_length=100)),
                ('nombre_transporte', models.CharField(max_length=100)),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
    ]
