# Generated by Django 5.1 on 2025-11-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cocacola', '0005_flota_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('cantidad_vendida', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cocacola.cliente', verbose_name='Cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cocacola.empleado', verbose_name='Empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cocacola.producto', verbose_name='Producto')),
            ],
        ),
    ]
